### ISSUE TITLE
Document raft/etcd Node Communication  

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#12]
Add a section to design about the exchange of messages from each embedded etcd node, paraphrase this from the etcd docs

**Comment by bkzhang** [comment]
I'll talk about both how the raft consensus works and manages replicated state machines and about how etcd discovers nodes. Am I missing anything else that might be related to message passing?

**Comment by JackyChiu** [comment]
@bkzhang I think @dipshit started adding a diagram of the communication, you can expand if wanted
