### ISSUE TITLE
Oral Presentation

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#13]
The master issue for the oral project presentation.

Due date: Monday January 27th 13:00
Place: ME4439
Presentation Time: 40mins total, 10mins each

https://docs.google.com/presentation/d/1GAygC_2qxZXKnqnEIGShTdEJQl-WvXejvznLP9jPE88/edit?folder=1jej2fqLoXSZQqpHjm2u7IBsirJQElFNO#slide=id.g7c27d6ab0c_1_11

The presentation should be largely backed by the motivation of the project.

- [x] brainstorm content 
- [x] slides?

**Comment by JackyChiu** [comment]
@dipshit can you add the nodes to this issue?

**Comment by dipshit** [comment]
### Motivation section
#### Assigned: VIKRAM
- Problem statement
- Why problem statement is worthy of being solved
- Why is go good? Contrast with C?
- Why is this thing useful?

### Goals / Requirements
#### Assigned: BRIAN
- What are we building
- How is it different from other solutions?
- What is the target application for this suite?
- Resilience (RAFT, ETCD)

### Design Section

#### Assigned: Kirin (dist. store), Jacky (service discovery), BRIAN (RAFT, ETCD)

- Service discovery
- Distributed storage
- RPC
- RAFT
- Why we chose certain designs

**Comment by vikrambombhi** [comment]
We need to add a slide for what we have done so far and what still needs to be done.

Some easy questions they might ask are:
- "How is this scalable" - scalability
- "how to know if something breaks" - reliability

**Comment by JackyChiu** [comment]
we didn't do so good
