### ISSUE TITLE
Add New Node 

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#15]
Research and experiment the steps needed to add a new node to an exsisting cluster. Document and and demonstrate this.

**Comment by JackyChiu** [comment]
Example of the 3 node cluster we spun up earlier in the project

https://github.com/edegens/ptype/tree/ca81ab66272924fd80eed29d000743b77e418922

**Comment by JackyChiu** [comment]
For project submission, we'd like to get this to the state where a new node can be spun up in the cluster and can determine if it needs to make a call to add itself to the cluster. (Added in #42)

The end-developer should be unaware of the order of programs being spun up, instead the configuration should guide this behaviour.

**Comment by bkzhang** [comment]
[adding 3rd node runtime reconfiguration](https://github.com/edegens/ptype/blob/e218a88e29d3ec6d2b89d33f3bbe1405b5170183/cluster/cluster_test.go#L145) where the error I get for adding 3rd node is 
<img width="696" alt="Screen Shot 2020-02-25 at 3 45 16 PM" src="https://user-images.githubusercontent.com/13925815/75287415-4fbc6f80-57e8-11ea-8a58-bf90e571a6df.png">

[starting 3rd node as part of the initial cluster](https://github.com/edegens/ptype/blob/089fb659c490c7854d7d22c40b27353e6f3f3dc9/cluster/cluster_test.go#L180) where the error I get for the 3rd node is 
<img width="692" alt="Screen Shot 2020-02-25 at 3 58 32 PM" src="https://user-images.githubusercontent.com/13925815/75287689-cf4a3e80-57e8-11ea-9b81-1650b0a6a5d3.png">

**Comment by JackyChiu** [comment]
> starting 3rd node as part of the initial cluster where the error I get for the 3rd node is

This doesn't work because your sequentially adding nodes. When you tell etcd you have an initial cluster, it will spin up the server and wait for the connection of those nodes. You can see in the logs, it's trying to connect to node2 and node3. In our implementation, we only exit `startEmbedEtcd` after the etcd node is ready. That's why the tests are hanging at https://github.com/edegens/ptype/blob/089fb659c490c7854d7d22c40b27353e6f3f3dc9/cluster/cluster_test.go#L133. 

We can solve this by spinning up 3 goroutines that each can `Join` with the appropriate configuration. Although, I don't understand the use case for this test `"test member add fails when the original InitialCluster when the cluster was dynamically reconfigured to have more members"`.

**Comment by JackyChiu** [comment]
> adding 3rd node runtime reconfiguration where the error I get for adding 3rd node is

I pushed up 76fcda0 that fixed this. The issue seems to be that there was not enough time for the new member of the cluster to gain quorum with the initial node. A new request to add a member during this resulted in a denied request due to it being unhealthy. This is a unfortunate gotcha because the etcdservers actually have an interval where they must be healthy before adding a new node. 

https://godoc.org/github.com/coreos/etcd/etcdserver#pkg-constants
```go
// HealthInterval is the minimum time the cluster should be healthy
// before accepting add member requests.
HealthInterval = 5 * time.Second
```

The other issue was that you were checking if the expected member add info was NOT equal to the result of the member add for node3 but the proceeded to use that invalid member add info to attempt to spin up node3. 
https://github.com/edegens/ptype/blob/e218a88e29d3ec6d2b89d33f3bbe1405b5170183/cluster/cluster_test.go#L155-L163

**Comment by bkzhang** [comment]
So I tested having `InitialCluster` as just 12380 and also having both 12380 and 22380 when adding 32380 and they both pass the test 🤷‍♂

**Comment by JackyChiu** [comment]
> So I tested having InitialCluster as just 12380 and also having both 12380 and 22380 when adding 32380 and they both pass the test 🤷‍♂

I'm not really sure what your trying to convey with this

**Comment by bkzhang** [comment]
it just seems like the adding requirement isn't too stringent and that it'll work as long as the original cluster nodes are listed somewhere in `InitialCluster`, although idk what happens if you remove one of the `InitialCluster` nodes

**Comment by bkzhang** [comment]
Add member should be changed to not have any logic regarding returning `MemberAddInfo`. When a user wants to this library they will first spin up a new node through `Join()` where:
1.  if the `peerURL` is in the `initialCluster` in the config then spin up etcd
2.  else make an `AddMember` reuest and spin up etcd if no error is returned
