### ISSUE TITLE
Liveness Checks

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#18]
Problem: We don't fully understand what the best way to approach liveness checks is.

Etcd does liveness checks in some sense with the master sending heartbeats to the peers in the cluster for the raft protocol, and we speculate it uses this to maintain an internal cluster registry. 

We want to figure out if it's possible to utilize this for our own service registry. How do others use etcd for service discovery and do liveness checks?

**Comment by JackyChiu** [comment]
# Lease Solution 

In etcd3, there is an introduction to the idea of leases. These are objects associated with keys in etcd that manage the TTL of the key. I'm purposing that we utilize leases for our service discovery. Here's a plan on how we can do so.

When registering a node to the cluster, we create a lease for it with a TTL. We insert it into etcd and we now have our node registered. We then spin up a goroutine that keeps the lease alive. We should have a graceful shutdown where the lease is removed and we will have the TTL as a fallback mechanism if our program/goroutine crashes. The other nodes in the cluster will keep consensus on the key and once one of them removes it from the expired TTL, it will be propagated. 

We can do this by utilizing the [`Grant`](https://godoc.org/github.com/coreos/etcd/clientv3#example-Lease--Grant) and [`KeepAlive`](https://godoc.org/github.com/coreos/etcd/clientv3#example-Lease--KeepAlive) APIs available in etcd's clientv3 package.

**Comment by vikrambombhi** [comment]
I actually like this idea. Im going to start reading the docs for this as well but i see nothing wrong with it. Good find!
