### ISSUE TITLE
Revisit Requirements section

### ISSUE THREAD

**Issue by dipshit** [edegens/ptype#70]
Here are some things I noticed:

- [x] 4.5.1 External Interfaces should talk about using the software, and Golang's tools for dependency management (go modules)

- [x] 4.2 Scope should say users provide their own computers

- [x] 4.4.3 - to short
- [x] 4.4.4 - to short
- [x] 4.4.5 - to short

- [x] 4.5.2 Functional Requirements: Add requirements we may have missed
 Add description to requirements that are too skimpy

- [x] 4.5.3 Performance Requirements maybe we can be more specific or realistic here now. Reference #5 

this issue can be closed when these changes are addressed, and the overall section has had more words added to it.

**Comment by vikrambombhi** [comment]
I don't know what to put in section 4.4.5 any ideas @dipshit  @JackyChiu  @bkzhang

**Comment by JackyChiu** [comment]
@vikrambombhi the assumptions are basically that the developers can handle the deployment, usage, anything that is outside the scope of our project

**Comment by bkzhang** [comment]
This can be closed, I left a comment though; we originally said the performance requirements can be achieved on macbook pro 2019, but we also said can scale 50 nodes on a single machine without noticeable performance decrease, i left both of those in but does anyone have a good guess to how many we can actually run or should I leave it at 50
