### ISSUE TITLE
[Design] Add a security section?

### ISSUE THREAD

**Issue by dipshit** [edegens/ptype#78]
Do we want a brief security section saying we did not much for it, and that it is up to the user? Do we want to talk about how it can be deployed in a secure manner eg. firewalls, client certs?

I'm leaning towards yes - but it would be a small section. I would also be down to omit this.

**Comment by JackyChiu** [comment]
I would not be oppose to it but i'd argue it's lower priority than the sections that we did focus on

**Comment by dipshit** [comment]
agreed, let's leave this open and see if we have time
