### ISSUE TITLE
Alternative Design Section

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#8]
Add explanation of why we're not doing DNS service discovery

**Comment by vikrambombhi** [comment]
I think this is already done in the Service Discovery section within the Design section

**Comment by JackyChiu** [comment]
@vikrambombhi yeah I did it yesterday, forgot to update board

**Comment by JackyChiu** [comment]
Done in https://docs.google.com/document/d/1uyd7m1bkvPEv_cIDi6jEcFdncJZUq7Y0_MvYxPoMtt4/edit#heading=h.fcy9rip4qwoa
