### ISSUE TITLE
[Design] Refactor Milestones & Timeline

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#81]
Milestones and timeline don't fit into the design section well. They should instead be moved to a section AFTER design which called "Project Timeline" or "Deliverables"

**Comment by JackyChiu** [comment]
@bkzhang @dipshit @vikrambombhi opinions?

**Comment by bkzhang** [comment]
I agree, this may also allow us to explain more on the complexity and any prerequisites in the design section and using it we can show how we came up with the timeline and deliverable ordering

**Comment by JackyChiu** [comment]
https://docs.google.com/document/d/1uyd7m1bkvPEv_cIDi6jEcFdncJZUq7Y0_MvYxPoMtt4/edit#heading=h.si3e72nmbfa9
