### ISSUE TITLE
[Implimentation] Verification testing

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#82]
We need to write about verification testing and our test suite in the implementation section. this could possibly be moved to a different section. 
- unit tests
- integration tests with spun up etcd
- we check for race conditions

**Comment by bkzhang** [comment]
should explain all the problems that occured with adding new nodes and the quorum, only idk how much of it we want to explain in #76 and which parts to put in verification

**Comment by JackyChiu** [comment]
> should explain all the problems that occured with adding new nodes and the quorum,

I want to leave this mostly in the implimentation section of etcd since that's where it's most relavent. this section should however discuss how the test suite enabled us to verify and test that feature

**Comment by bkzhang** [comment]
or what we can do is talk about adding nodes, the network partitioning and then point to the testing section saying how we discovered problems via testing and then continue with how we fixed it

**Comment by bkzhang** [comment]
> > should explain all the problems that occured with adding new nodes and the quorum,
> 
> I want to leave this mostly in the implimentation section of etcd since that's where it's most relavent. this section should however discuss how the test suite enabled us to verify and test that feature

**Comment by bkzhang** [comment]
oops

**Comment by JackyChiu** [comment]
https://docs.google.com/document/d/1uyd7m1bkvPEv_cIDi6jEcFdncJZUq7Y0_MvYxPoMtt4/edit#heading=h.2i0nibhg7a5g
